fn create context oci-context --provider oracle
fn update context oci-context oracle.region us-ashburn-1
fn update context oci-context oracle.compartment-id <COMPARTMENT_OCID>
fn use context oci-context

[opc@oci-admin-01 ~]$ fn update context oci-context oracle.region us-ashburn-1

Fn: open /home/opc/.fn/contexts/.yaml: no such file or directory

See 'fn <command> --help' for more information. Client version: 0.6.43
[opc@oci-admin-01 ~]$

fn update context oci-context api-url https://functions.us-ashburn-1.oci.oraclecloud.com

fn create context oci-context --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com

fn create context oci-context \
  --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com \
  --oracle.region us-ashburn-1 \
  --oracle.compartment-id ocid1.compartment.oc1..aaaaaaaal3ny7cdvz3ovgcq43x7vqexyyy4s2fozfo4zhked7xsyzbhsx7bq

Option 2 â€” Create + Edit YAML
bash
Kopieren
Bearbeiten
fn create context oci-context \
  --provider oracle \
  --api-url https://functions.us-ashburn-1.oci.oraclecloud.com

nano ~/.fn/contexts/oci-context.yaml
Then manually add:

yaml
Kopieren
Bearbeiten
oracle.region: us-ashburn-1
oracle.compartment-id: <COMPARTMENT_OCID>

fn config function cloud-guard-processing-app cloud_guard_processor BUCKET_NAME cloud-guard-findings-bucket

Successfully created function: cloud_guard_processor with iad.ocir.io/acscloudengineering/cloud-guard-functions/cloud_guard_processor:0.0.4
[opc@oci-admin-01 cloud_guard_processor]$ fn invoke cloud-guard-processing-app cloud_guard_processor
Error invoking function. status: 502 message: function failed

oci logging search-logs \
  --search-query "search \"FunctionsExecution\" where appName = 'cloud-guard-processing-app'" \
  --time-start 10m


echo "_L>Dr8F-m8_]YrN>TaF8" | docker login iad.ocir.io  \
--username "acscloudengineering/gregory.ohwerhi@oracle.com" \
--password-stdin

tZ[-RP#I#TOieRz79SmC

echo "tZ[-RP#I#TOieRz79SmC" | docker login iad.ocir.io  \
--username "acscloudengineering/gregory.ohwerhi@oracle.com" \
--password-stdin

echo "tZ[-RP#I#TOieRz79SmC" | docker login iad.ocir.io  --username "acscloudengineering/oracleidentitycloudservice/gregory.ohwerhi@oracle.com" --password-stdin

[opc@oci-admin-01 cloud_guard_processor]$ echo '{"finding":"test"}' | fn invoke cloud-guard-processing-app cloud_guard_processor
Error: {'target_service': 'object_storage', 'status': 404, 'code': 'BucketNotFound', 'opc-request-id': 'iad-1:2Kats6lJBJf6Wj0gTxrwpo-dXoP0epgmfsbFx-xilfZaUskGPuks689lbQudxNs8', 'message': "Either the bucket named 'cloud-guard-findings-bucket' does not exist in the namespace 'acscloudengineering' or you are not authorized to access it", 'operation_name': 'put_object', 'timestamp': '2025-08-18T09:15:41.614311+00:00', 'client_version': 'Oracle-PythonSDK/2.158.0', 'request_endpoint': 'PUT https://objectstorage.us-ashburn-1.oraclecloud.com/n/acscloudengineering/b/cloud-guard-findings-bucket/o/2025-08-18T09-15-41Z_unknown_finding.json', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_bucketnotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Object/PutObject for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}



echo '{"id":"finding-test","severity":"HIGH"}' | fn invoke cloud-guard-processing-app cloud_guard_processor

[opc@oci-admin-01 cloud_guard_processor]$ echo '{"id":"finding-test"}' |DEBUG=1 fn invoke cloud-guard-processing-app cloud_guard_processor
POST /20181201/functions/ocid1.fnfunc.oc1.iad.aaaaaaaaanek6owb3wzp6yiljtyp3fnmtgj6ywghigm524hpxb6s3fyjqvhq/actions/invoke HTTP/1.1
Host: ob3xlmlev3a.us-ashburn-1.functions.oci.oraclecloud.com
User-Agent: Go-http-client/1.1
Content-Length: 22
Content-Type: text/plain
Accept-Encoding: gzip

{"id":"finding-test"}

HTTP/1.1 502 Bad Gateway
Content-Length: 68
Content-Type: application/json
Date: Wed, 27 Aug 2025 07:25:55 GMT
Fn-Call-Id: 01K3N6PGVN1BT1358ZJ0002QEJ
Opc-Request-Id: /01K3N6PGSM0000000000005CCV/01K3N6PGSM0000000000005CCW

{"code":"FunctionInvokeExecutionFailed","message":"function failed"}
Error invoking function. status: 502 message: function failed

"01K3NA5BWY1BT155GZJ0001BWH - fn - ERROR - inconsistent use of tabs and spaces in indentation (func.py, line 25):  File \"/python/fdk/runner.py\", line 74, in handle_request\\n    response_data = await with_deadline(ctx, handler_code, body)\\n  File \"/python/fdk/runner.py\", line 54, in with_deadline\\n    raise ex\\n  File \"/python/fdk/runner.py\", line 47, in with_deadline\\n    handle_func = handler_code.handler()\\n  File \"/python/fdk/customer_code.py\", line 94, in handler\\n    mod = self._delayed_module_class.get_module()\\n  File \"/python/fdk/customer_code.py\", line 58, in get_module\\n    self._func_module = SourceFileLoader(fname, self._mod_path)\\\\n  File \"<frozen importlib._bootstrap_external>\", line 529, in _check_name_wrapper\\n  File \"<frozen importlib._bootstrap_external>\", line 1030, in load_module\\n  File \"<frozen importlib._bootstrap_external>\", line 854, in load_module\\n  File \"<frozen importlib._bootstrap>\", line 274, in _load_module_shim\\n  File \"<frozen importlib._bootstrap>\", line 711, in _load\\n  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\\n  File \"<frozen importlib._bootstrap_external>\", line 846, in exec_module\\n  File \"<frozen importlib._bootstrap_external>\", line 983, in get_code\\n  File \"<frozen importlib._bootstrap_external>\", line 913, in source_to_code\\n  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\\n"

{
  "datetime": 1756283240094,
  "logContent": {
    "data": {
      "applicationId": "ocid1.fnapp.oc1.iad.aaaaaaaarkxww5zfglqxdkhdttctsums7rzdkbzxxkm67chbqob3xlmlev3a",
      "containerId": "01K3NA6EBF00000000000000SH",
      "functionId": "ocid1.fnfunc.oc1.iad.aaaaaaaaanek6owb3wzp6yiljtyp3fnmtgj6ywghigm524hpxb6s3fyjqvhq",
      "message": "01K3NA5BWY1BT155GZJ0001BWH - fn - ERROR - inconsistent use of tabs and spaces in indentation (func.py, line 25):  File \"/python/fdk/runner.py\", line 74, in handle_request\\n    response_data = await with_deadline(ctx, handler_code, body)\\n  File \"/python/fdk/runner.py\", line 54, in with_deadline\\n    raise ex\\n  File \"/python/fdk/runner.py\", line 47, in with_deadline\\n    handle_func = handler_code.handler()\\n  File \"/python/fdk/customer_code.py\", line 94, in handler\\n    mod = self._delayed_module_class.get_module()\\n  File \"/python/fdk/customer_code.py\", line 58, in get_module\\n    self._func_module = SourceFileLoader(fname, self._mod_path)\\\\n  File \"<frozen importlib._bootstrap_external>\", line 529, in _check_name_wrapper\\n  File \"<frozen importlib._bootstrap_external>\", line 1030, in load_module\\n  File \"<frozen importlib._bootstrap_external>\", line 854, in load_module\\n  File \"<frozen importlib._bootstrap>\", line 274, in _load_module_shim\\n  File \"<frozen importlib._bootstrap>\", line 711, in _load\\n  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\\n  File \"<frozen importlib._bootstrap_external>\", line 846, in exec_module\\n  File \"<frozen importlib._bootstrap_external>\", line 983, in get_code\\n  File \"<frozen importlib._bootstrap_external>\", line 913, in source_to_code\\n  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\\n",
      "opcRequestId": "/01K3NA5BV600000000000033V2/01K3NA5BV600000000000033V3",
      "requestId": "/01K3NA5BV600000000000033V2/01K3NA5BV600000000000033V3",
      "src": "STDERR"
    },
    "id": "4a08244b-c97c-4ea2-a85a-8acec8139862",
    "oracle": {
      "compartmentid": "ocid1.compartment.oc1..aaaaaaaal3ny7cdvz3ovgcq43x7vqexyyy4s2fozfo4zhked7xsyzbhsx7bq",
      "ingestedtime": "2025-08-27T08:27:24.869Z",
      "loggroupid": "ocid1.loggroup.oc1.iad.amaaaaaa3vux2giawc2yzxo5rqacetrng47qkupddp4gt6ccp5mbvocfrhha",
      "logid": "ocid1.log.oc1.iad.amaaaaaa3vux2gia6qcaipq52e2klhlemmdwadhxffomcgdfcxwt3whchknq",
      "tenantid": "ocid1.tenancy.oc1..aaaaaaaaabc4esylkbw3jkbquuluuq4iftuuwnfc2yg2fguo4s7j43exv6pq"
    },
    "source": "cloud-guard-processing-app",
    "specversion": "1.0",
    "subject": "cloud_guard_processor",
    "time": "2025-08-27T08:27:20.094Z",
    "type": "com.oraclecloud.functions.application.functioninvoke"
  },
  "regionId": "us-ashburn-1"
}

"Served function invocation request in 53.021 seconds with error code 502 - FunctionInvokeExecutionFailed (502): function failed "
{
  "datetime": 1756283240122,
  "logContent": {
    "data": {
      "applicationId": "ocid1.fnapp.oc1.iad.aaaaaaaarkxww5zfglqxdkhdttctsums7rzdkbzxxkm67chbqob3xlmlev3a",
      "containerId": "n/a",
      "functionId": "ocid1.fnfunc.oc1.iad.aaaaaaaaanek6owb3wzp6yiljtyp3fnmtgj6ywghigm524hpxb6s3fyjqvhq",
      "message": "Served function invocation request in 53.021 seconds with error code 502 - FunctionInvokeExecutionFailed (502): function failed ",
      "opcRequestId": "/01K3NA5BV600000000000033V2/01K3NA5BV600000000000033V3",
      "requestId": "/01K3NA5BV600000000000033V2/01K3NA5BV600000000000033V3",
      "src": "stdout"
    },
    "id": "e2058f29-591b-4b1e-bd28-c0ca46676abf",
    "oracle": {
      "compartmentid": "ocid1.compartment.oc1..aaaaaaaal3ny7cdvz3ovgcq43x7vqexyyy4s2fozfo4zhked7xsyzbhsx7bq",
      "ingestedtime": "2025-08-27T08:27:21.400Z",
      "loggroupid": "ocid1.loggroup.oc1.iad.amaaaaaa3vux2giawc2yzxo5rqacetrng47qkupddp4gt6ccp5mbvocfrhha",
      "logid": "ocid1.log.oc1.iad.amaaaaaa3vux2gia6qcaipq52e2klhlemmdwadhxffomcgdfcxwt3whchknq",
      "tenantid": "ocid1.tenancy.oc1..aaaaaaaaabc4esylkbw3jkbquuluuq4iftuuwnfc2yg2fguo4s7j43exv6pq"
    },
    "source": "cloud-guard-processing-app",
    "specversion": "1.0",
    "subject": "cloud_guard_processor",
    "time": "2025-08-27T08:27:20.122Z",
    "type": "com.oraclecloud.functions.application.functioninvoke"
  },
  "regionId": "us-ashburn-1"
}

Error: {'target_service': 'object_storage', 'status': 404, 'code': 'NamespaceNotFound', 'opc-request-id': 'iad-1:WjXfGAtgi6BYLOhw1XWLHZNJfRZ_BK1F3pw_FTtLU7IUVHQHwyVmfcx5H3jAIG_8', 'message': 'You do not have authorization to perform this request, or the requested resource could not be found.', 'operation_name': 'list_buckets', 'timestamp': '2025-08-27T08:40:01.663956+00:00', 'client_version': 'Oracle-PythonSDK/2.158.0', 'request_endpoint': 'GET https://objectstorage.us-ashburn-1.oraclecloud.com/n/acscloudengineering/b', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_namespacenotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Bucket/ListBuckets for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}
Error: {'target_service': 'object_storage', 'status': 404, 'code': 'NamespaceNotFound', 'opc-request-id': 'iad-1:WjXfGAtgi6BYLOhw1XWLHZNJfRZ_BK1F3pw_FTtLU7IUVHQHwyVmfcx5H3jAIG_8', 'message': 'You do not have authorization to perform this request, or the requested resource could not be found.', 'operation_name': 'list_buckets', 'timestamp': '2025-08-27T08:40:01.663956+00:00', 'client_version': 'Oracle-PythonSDK/2.158.0', 'request_endpoint': 'GET https://objectstorage.us-ashburn-1.oraclecloud.com/n/acscloudengineering/b', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': "See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_namespacenotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Bucket/ListBuckets for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message."}


"01K3NKK3M41BT1460ZJ000JMEN - root - ERROR - Error processing event: {'target_service': 'object_storage', 'status': 404, 'code': 'NamespaceNotFound', 'opc-request-id': 'iad-1:FscVmZO-N9PJ2SOHRwgneou6_a8hq82zFbaQp_WC26UDw6gsqJKQzqg_P8kPyi6J', 'message': 'You do not have authorization to perform this request, or the requested resource could not be found.', 'operation_name': 'list_buckets', 'timestamp': '2025-08-27T11:11:53.631865+00:00', 'client_version': 'Oracle-PythonSDK/2.158.0', 'request_endpoint': 'GET https://objectstorage.us-ashburn-1.oraclecloud.com/n/acscloudengineering/b', 'logging_tips': 'To get more info on the failing request, refer to https://docs.oracle.com/en-us/iaas/tools/python/latest/logging.html for ways to log the request/response details.', 'troubleshooting_tips': \"See https://docs.oracle.com/iaas/Content/API/References/apierrors.htm#apierrors_404__404_namespacenotfound for more information about resolving this error. Also see https://docs.oracle.com/iaas/api/#/en/objectstorage/20160918/Bucket/ListBuckets for details on this operation's requirements. If you are unable to resolve this object_storage issue, please contact Oracle support and provide them this full error message.\"}"
"01K3NKK3M41BT1460ZJ000JMEN - oci.circuit_breaker.circuit_breaker - DEBUG - status code:404 not in failure_statuses_and_codes:{409: ['IncorrectState'], 429: [], 500: [], 502: [], 503: [], 504: []}"
"01K3NKK3M41BT1460ZJ000JMEN - oci.circuit_breaker.circuit_breaker - DEBUG - Is transient error status code:404 error code:NamespaceNotFound"
"01K3NKK3M41BT1460ZJ000JMEN - oci._vendor.urllib3.connectionpool - DEBUG - https://objectstorage.us-ashburn-1.oraclecloud.com:443 \"GET /n/acscloudengineering/b?compartmentId=ocid1.compartment.oc1..aaaaaaaal3ny7cdvz3ovgcq43x7vqexyyy4s2fozfo4zhked7xsyzbhsx7bq HTTP/1.1\" 404 141"
"01K3NKK3M41BT1460ZJ000JMEN - root - INFO - Resolved Namespace: acscloudengineering"
"01K3NKK3M41BT1460ZJ000JMEN - oci._vendor.urllib3.connectionpool - DEBUG - https://objectstorage.us-ashburn-1.oraclecloud.com:443 \"GET /n HTTP/1.1\" 200 21"
"01K3NKK3M41BT1460ZJ000JMEN - oci._vendor.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): objectstorage.us-ashburn-1.oraclecloud.com:443"
"01K3NKK3M41BT1460ZJ000JMEN - root - INFO - Signer: <oci.auth.signers.ephemeral_resource_principals_signer.EphemeralResourcePrincipalSigner object at 0x7f94e6f09c40>"
"01K3NKK3M41BT1460ZJ000JMEN - root - INFO - Event received: {'id': 'finding-test'}"


{
  "eventType": "com.oraclecloud.cloudguard.problemdetected",
  "cloudEventsVersion": "0.1",
  "eventTypeVersion": "2.0",
  "source": "CloudGuardResponderEngine",
  "eventTime": "2025-08-28T12:45:22Z",
  "contentType": "application/json",
  "data": {
    "compartmentId": "ocid1.compartment.oc1..aaaaaaaaf3t5nho53gfnagagdezv6tz2ltkup3lfoqt3vpwlep3mttk2pg4a",
    "compartmentName": "OCI-LAB-68",
    "resourceName": "VNIC without associated network security group",
    "resourceId": "ocid1.cloudguardproblem.oc1.iad.amaaaaaa3vux2gkqaughslks7pp6w2asjyjohnh7v7bpjalrwqetwsdvdf3q",
    "additionalDetails": {
      "tenantId": "ocid1.tenancy.oc1..aaaaaaaaabc4esylkbw3jkbquuluuq4iftuuwnfc2yg2fguo4s7j43exv6pq",
      "status": "OPEN",
      "reason": "New Problem detected by CloudGuard",
      "problemName": "VNIC_WITHOUT_NETWORK_SECURITY_GROUP",
      "riskLevel": "MINOR",
      "problemType": "CONFIG_CHANGE",
      "resourceName": "kamei-instance-20250828-1639",
      "resourceId": "ocid1.vnic.oc1.iad.abuwcljsduxzfy6mikytrbzbyzmk47nwd5zpshzmavuwor435ypdinw4uftq",
      "resourceType": "Instance",
      "targetId": "ocid1.cloudguardtarget.oc1.iad.amaaaaaa3vux2gianda6fvrdjodb77xzyzi2373fjifkv7varo7a4h46xvaq",
      "labels": "COMPUTE, Network",
      "firstDetected": "2025-08-28T12:45:15.330Z",
      "lastDetected": "2025-08-28T12:45:15.330Z",
      "region": "us-ashburn-1",
      "problemDescription": "A virtual network interface card (VNIC) is\u00a0a networking component that enables a resource such as a compute instance to connect to a virtual cloud network (VCN). The VNIC determines how the instance connects with endpoints inside and outside the VCN. Each VNIC resides in a subnet in a VCN. An VNIC with an NSG may trigger a connectivity issue.",
      "problemRecommendation": "Ensure that the missing NSG association from this VNIC is expected."
    }
  },
  "eventID": "d0f630fd-7169-476e-8a65-5db27d95c20c",
  "extensions": {
    "compartmentId": "ocid1.compartment.oc1..aaaaaaaaf3t5nho53gfnagagdezv6tz2ltkup3lfoqt3vpwlep3mttk2pg4a"
  }
}

allow any-user to inspect compartments in tenancy
  where all {request.principal.type = 'analyticsinstance',
            request.principal.id = '<OAC_INSTANCE_OCID>'}

allow any-user to read objectstorage-namespaces in tenancy
  where all {request.principal.type = 'analyticsinstance',
            request.principal.id = '<OAC_INSTANCE_OCID>'}


allow any-user to read buckets in compartment <BucketCompartment>
  where all {request.principal.type = 'analyticsinstance',
            request.principal.id = '<OAC_INSTANCE_OCID>'}

allow any-user to read objects in compartment <BucketCompartment>
  where all {request.principal.type = 'analyticsinstance',
            request.principal.id = '<OAC_INSTANCE_OCID>'}

cat > test_findings.csv <<'CSV'
eventTime,tenantId,compartmentId,compartmentName,region,detectorType,detectorRuleId,problemId,problemName,severity,severityRank,riskLevel,resourceType,resourceId,lifecycleState,recommendation,firstDetected,lastDetected,tagsJson,payloadVersion
2025-08-28T12:45:22Z,ocid1.tenancy.oc1..aaaaaaaaabc4esylkbw3jkbquuluuq4iftuuwnfc2yg2fguo4s7j43exv6pq,ocid1.compartment.oc1..aaaaaaaaf3t5nho53gfnagagdezv6tz2ltkup3lfoqt3vpwlep3mttk2pg4a,OCI-LAB-68,us-ashburn-1,,,,ocid1.cloudguardproblem.oc1.iad.amaaaaaa3vux2gkqaughslks7pp6w2asjyjohnh7v7bpjalrwqetwsdvdf3q,VNIC_WITHOUT_NETWORK_SECURITY_GROUP,,2,MINOR,Instance,ocid1.vnic.oc1.iad.abuwcljsduxzfy6mikytrbzbyzmk47nwd5zpshzmavuwor435ypdinw4uftq,OPEN,"Ensure that the missing NSG association from this VNIC is expected.",2025-08-28T12:45:15.330Z,2025-08-28T12:45:15.330Z,"{""labels"":""COMPUTE, Network""}",2.0
CSV

# optional: see your namespace
oci os ns get

# upload under a partitioned path OAC can browse
oci os object put \
  -bn cloud-guard-findings-bucket \
  --file test_findings.csv \
  --name dt=2025-08-28/hr=12/findings_test.csv \
  --content-type "text/csv; charset=utf-8"

[opc@oci-admin-01 cloud_guard_processor]$ export FN_REGISTRY=iad.ocir.io/acscloudengineering/cloud-guard-functions                                                                   [opc@oci-admin-01 cloud_guard_processor]$ echo "tZ[-RP#I#TOieRz79SmC" | docker login iad.ocir.io  --username "acscloudengineering/oracleidentitycloudservice/gregory.ohwerhi@oracle.com" --password-stdin
WARNING! Your password will be stored unencrypted in /home/opc/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
[opc@oci-admin-01 cloud_guard_processor]$ fn -v deploy --app cloud-guard-processing-app

[opc@oci-admin-01 cloud_guard_processor]$ echo '{"id":"finding-test"}' |DEBUG=1 fn invoke cloud-guard-processing-app cloud_guard_processor

01K44K3R791BT1460ZJ019RR1S - fn - ERROR - unmatched '}' (func.py, line 103): File "/python/fdk/runner.py", line 74, in handle_request\n response_data = await with_deadline(ctx, handler_code, body)\n File "/python/fdk/runner.py", line 54, in with_deadline\n raise ex\n File "/python/fdk/runner.py", line 47, in with_deadline\n handle_func = handler_code.handler()\n File "/python/fdk/customer_code.py", line 94, in handler\n mod = self._delayed_module_class.get_module()\n File "/python/fdk/customer_code.py", line 58, in get_module\n self._func_module = SourceFileLoader(fname, self._mod_path)\\n File "<frozen importlib._bootstrap_external>", line 529, in _check_name_wrapper\n File "<frozen importlib._bootstrap_external>", line 1030, in load_module\n File "<frozen importlib._bootstrap_external>", line 854, in load_module\n File "<frozen importlib._bootstrap>", line 274, in _load_module_shim\n File "<frozen importlib._bootstrap>", line 711, in _load\n File "<frozen importlib._bootstrap>", line 680, in _load_unlocked\n File "<frozen importlib._bootstrap_external>", line 846, in exec_module\n File "<frozen importlib._bootstrap_external>", line 983, in get_code\n File "<frozen importlib._bootstrap_external>", line 913, in source_to_code\n File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed\n

# First batch (up to 200 objects)
RESP=$(echo '{"action":"backfill","max":200}' | fn invoke cloud-guard-processing-app cloud_guard_processor)
echo "$RESP"
NEXT=$(echo "$RESP" | python -c 'import sys,json; print(json.load(sys.stdin).get("next_start",""))')

# Loop until done
while [ -n "$NEXT" ]; do
  echo "Continuing from: $NEXT"
  RESP=$(echo "{\"action\":\"backfill\",\"max\":200,\"resume_from\":\"$NEXT\"}" | fn invoke cloud-guard-processing-app cloud_guard_processor)
  echo "$RESP"
  NEXT=$(echo "$RESP" | python -c 'import sys,json; print(json.load(sys.stdin).get("next_start",""))')
done

Continuing from: state/last_processed_key.txt
{"processed": 0, "next_start": "state/last_processed_key.txt", "last_key": "state/last_processed_key.txt", "done": true}
